/*
 * generated by Xtext 2.25.0
 */
package org.xtext.coursework.storyLang;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class StoryStandaloneSetup extends StoryStandaloneSetupGenerated {

	public static void doSetup() {
		new StoryStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
