/*
 * generated by Xtext 2.30.0
 */
package org.xtext.coursework.storyLang.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.coursework.storyLang.ui.internal.StoryLangActivator;

public class StoryUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return StoryLangActivator.getInstance().getInjector("org.xtext.coursework.storyLang.Story");
	}

}
