/*
 * generated by Xtext 2.25.0
 */
package org.xtext.coursework.storyLang.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class StoryUiModule extends AbstractStoryUiModule {

	public StoryUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
