/*
 * generated by Xtext 2.30.0
 */
package org.xtext.coursework.storyLang.ui

import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
class StoryUiModule extends AbstractStoryUiModule {
}
