/*
 * generated by Xtext 2.25.0
 */
package org.xtext.coursework.storyLang.ide;


/**
 * Use this class to register ide components.
 */
public class StoryIdeModule extends AbstractStoryIdeModule {
}
