/*
 * generated by Xtext 2.25.0
 */
package org.xtext.coursework.storyLang.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.coursework.storyLang.StoryRuntimeModule;
import org.xtext.coursework.storyLang.StoryStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class StoryIdeSetup extends StoryStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new StoryRuntimeModule(), new StoryIdeModule()));
	}
	
}
