/*
 * generated by Xtext 2.25.0
 */
package org.xtext.coursework.storyLang.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class StoryGrammarAccess extends AbstractElementFinder.AbstractGrammarElementFinder {
	
	public class StoryProgramElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.coursework.storyLang.Story.StoryProgram");
		private final Assignment cStatementsAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cStatementsStatementParserRuleCall_0 = (RuleCall)cStatementsAssignment.eContents().get(0);
		
		//StoryProgram:
		//    statements += Statement*
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//statements += Statement*
		public Assignment getStatementsAssignment() { return cStatementsAssignment; }
		
		//Statement
		public RuleCall getStatementsStatementParserRuleCall_0() { return cStatementsStatementParserRuleCall_0; }
	}
	public class StatementElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.coursework.storyLang.Story.Statement");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cNameStatementParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cEmotionStatementParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cVerbStatementParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		private final RuleCall cAdverbStatementParserRuleCall_3 = (RuleCall)cAlternatives.eContents().get(3);
		private final RuleCall cAdjectiveStatementParserRuleCall_4 = (RuleCall)cAlternatives.eContents().get(4);
		private final RuleCall cLocationStatementParserRuleCall_5 = (RuleCall)cAlternatives.eContents().get(5);
		
		//Statement:
		//    NameStatement |
		//    EmotionStatement |
		//    VerbStatement |
		//    AdverbStatement |
		//    AdjectiveStatement |
		//    LocationStatement
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//NameStatement |
		//EmotionStatement |
		//VerbStatement |
		//AdverbStatement |
		//AdjectiveStatement |
		//LocationStatement
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//NameStatement
		public RuleCall getNameStatementParserRuleCall_0() { return cNameStatementParserRuleCall_0; }
		
		//EmotionStatement
		public RuleCall getEmotionStatementParserRuleCall_1() { return cEmotionStatementParserRuleCall_1; }
		
		//VerbStatement
		public RuleCall getVerbStatementParserRuleCall_2() { return cVerbStatementParserRuleCall_2; }
		
		//AdverbStatement
		public RuleCall getAdverbStatementParserRuleCall_3() { return cAdverbStatementParserRuleCall_3; }
		
		//AdjectiveStatement
		public RuleCall getAdjectiveStatementParserRuleCall_4() { return cAdjectiveStatementParserRuleCall_4; }
		
		//LocationStatement
		public RuleCall getLocationStatementParserRuleCall_5() { return cLocationStatementParserRuleCall_5; }
	}
	public class NameStatementElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.coursework.storyLang.Story.NameStatement");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cNameKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cValueAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cValueSTRINGTerminalRuleCall_1_0 = (RuleCall)cValueAssignment_1.eContents().get(0);
		private final Keyword cSemicolonKeyword_2 = (Keyword)cGroup.eContents().get(2);
		
		//NameStatement:
		//    'name:' value=STRING ';'
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'name:' value=STRING ';'
		public Group getGroup() { return cGroup; }
		
		//'name:'
		public Keyword getNameKeyword_0() { return cNameKeyword_0; }
		
		//value=STRING
		public Assignment getValueAssignment_1() { return cValueAssignment_1; }
		
		//STRING
		public RuleCall getValueSTRINGTerminalRuleCall_1_0() { return cValueSTRINGTerminalRuleCall_1_0; }
		
		//';'
		public Keyword getSemicolonKeyword_2() { return cSemicolonKeyword_2; }
	}
	public class EmotionStatementElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.coursework.storyLang.Story.EmotionStatement");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cEmotionsKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cListAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cListSTRINGTerminalRuleCall_1_0 = (RuleCall)cListAssignment_1.eContents().get(0);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cCommaKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Assignment cListAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final RuleCall cListSTRINGTerminalRuleCall_2_1_0 = (RuleCall)cListAssignment_2_1.eContents().get(0);
		private final Keyword cSemicolonKeyword_3 = (Keyword)cGroup.eContents().get(3);
		
		//EmotionStatement:
		//    'emotions:' list+=STRING (',' list+=STRING )* ';'
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'emotions:' list+=STRING (',' list+=STRING )* ';'
		public Group getGroup() { return cGroup; }
		
		//'emotions:'
		public Keyword getEmotionsKeyword_0() { return cEmotionsKeyword_0; }
		
		//list+=STRING
		public Assignment getListAssignment_1() { return cListAssignment_1; }
		
		//STRING
		public RuleCall getListSTRINGTerminalRuleCall_1_0() { return cListSTRINGTerminalRuleCall_1_0; }
		
		//(',' list+=STRING )*
		public Group getGroup_2() { return cGroup_2; }
		
		//','
		public Keyword getCommaKeyword_2_0() { return cCommaKeyword_2_0; }
		
		//list+=STRING
		public Assignment getListAssignment_2_1() { return cListAssignment_2_1; }
		
		//STRING
		public RuleCall getListSTRINGTerminalRuleCall_2_1_0() { return cListSTRINGTerminalRuleCall_2_1_0; }
		
		//';'
		public Keyword getSemicolonKeyword_3() { return cSemicolonKeyword_3; }
	}
	public class VerbStatementElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.coursework.storyLang.Story.VerbStatement");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cVerbKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cListAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cListSTRINGTerminalRuleCall_1_0 = (RuleCall)cListAssignment_1.eContents().get(0);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cCommaKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Assignment cListAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final RuleCall cListSTRINGTerminalRuleCall_2_1_0 = (RuleCall)cListAssignment_2_1.eContents().get(0);
		private final Keyword cSemicolonKeyword_3 = (Keyword)cGroup.eContents().get(3);
		
		//VerbStatement:
		//    'verb:' list+=STRING (',' list+=STRING )* ';'
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'verb:' list+=STRING (',' list+=STRING )* ';'
		public Group getGroup() { return cGroup; }
		
		//'verb:'
		public Keyword getVerbKeyword_0() { return cVerbKeyword_0; }
		
		//list+=STRING
		public Assignment getListAssignment_1() { return cListAssignment_1; }
		
		//STRING
		public RuleCall getListSTRINGTerminalRuleCall_1_0() { return cListSTRINGTerminalRuleCall_1_0; }
		
		//(',' list+=STRING )*
		public Group getGroup_2() { return cGroup_2; }
		
		//','
		public Keyword getCommaKeyword_2_0() { return cCommaKeyword_2_0; }
		
		//list+=STRING
		public Assignment getListAssignment_2_1() { return cListAssignment_2_1; }
		
		//STRING
		public RuleCall getListSTRINGTerminalRuleCall_2_1_0() { return cListSTRINGTerminalRuleCall_2_1_0; }
		
		//';'
		public Keyword getSemicolonKeyword_3() { return cSemicolonKeyword_3; }
	}
	public class AdverbStatementElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.coursework.storyLang.Story.AdverbStatement");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cAdverbsKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cListAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cListSTRINGTerminalRuleCall_1_0 = (RuleCall)cListAssignment_1.eContents().get(0);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cCommaKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Assignment cListAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final RuleCall cListSTRINGTerminalRuleCall_2_1_0 = (RuleCall)cListAssignment_2_1.eContents().get(0);
		private final Keyword cSemicolonKeyword_3 = (Keyword)cGroup.eContents().get(3);
		
		//AdverbStatement:
		//    'adverbs:' list+=STRING (',' list+=STRING )* ';'
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'adverbs:' list+=STRING (',' list+=STRING )* ';'
		public Group getGroup() { return cGroup; }
		
		//'adverbs:'
		public Keyword getAdverbsKeyword_0() { return cAdverbsKeyword_0; }
		
		//list+=STRING
		public Assignment getListAssignment_1() { return cListAssignment_1; }
		
		//STRING
		public RuleCall getListSTRINGTerminalRuleCall_1_0() { return cListSTRINGTerminalRuleCall_1_0; }
		
		//(',' list+=STRING )*
		public Group getGroup_2() { return cGroup_2; }
		
		//','
		public Keyword getCommaKeyword_2_0() { return cCommaKeyword_2_0; }
		
		//list+=STRING
		public Assignment getListAssignment_2_1() { return cListAssignment_2_1; }
		
		//STRING
		public RuleCall getListSTRINGTerminalRuleCall_2_1_0() { return cListSTRINGTerminalRuleCall_2_1_0; }
		
		//';'
		public Keyword getSemicolonKeyword_3() { return cSemicolonKeyword_3; }
	}
	public class LocationStatementElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.coursework.storyLang.Story.LocationStatement");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cLocationsKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cListAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cListSTRINGTerminalRuleCall_1_0 = (RuleCall)cListAssignment_1.eContents().get(0);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cCommaKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Assignment cListAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final RuleCall cListSTRINGTerminalRuleCall_2_1_0 = (RuleCall)cListAssignment_2_1.eContents().get(0);
		private final Keyword cSemicolonKeyword_3 = (Keyword)cGroup.eContents().get(3);
		
		//LocationStatement:
		//    'locations:' list+=STRING (',' list+=STRING )* ';'
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'locations:' list+=STRING (',' list+=STRING )* ';'
		public Group getGroup() { return cGroup; }
		
		//'locations:'
		public Keyword getLocationsKeyword_0() { return cLocationsKeyword_0; }
		
		//list+=STRING
		public Assignment getListAssignment_1() { return cListAssignment_1; }
		
		//STRING
		public RuleCall getListSTRINGTerminalRuleCall_1_0() { return cListSTRINGTerminalRuleCall_1_0; }
		
		//(',' list+=STRING )*
		public Group getGroup_2() { return cGroup_2; }
		
		//','
		public Keyword getCommaKeyword_2_0() { return cCommaKeyword_2_0; }
		
		//list+=STRING
		public Assignment getListAssignment_2_1() { return cListAssignment_2_1; }
		
		//STRING
		public RuleCall getListSTRINGTerminalRuleCall_2_1_0() { return cListSTRINGTerminalRuleCall_2_1_0; }
		
		//';'
		public Keyword getSemicolonKeyword_3() { return cSemicolonKeyword_3; }
	}
	public class AdjectiveStatementElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.coursework.storyLang.Story.AdjectiveStatement");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cAdjectivesKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cListAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cListSTRINGTerminalRuleCall_1_0 = (RuleCall)cListAssignment_1.eContents().get(0);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cCommaKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Assignment cListAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final RuleCall cListSTRINGTerminalRuleCall_2_1_0 = (RuleCall)cListAssignment_2_1.eContents().get(0);
		private final Keyword cSemicolonKeyword_3 = (Keyword)cGroup.eContents().get(3);
		
		//AdjectiveStatement:
		//    'adjectives:' list+=STRING (',' list+=STRING )* ';'
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'adjectives:' list+=STRING (',' list+=STRING )* ';'
		public Group getGroup() { return cGroup; }
		
		//'adjectives:'
		public Keyword getAdjectivesKeyword_0() { return cAdjectivesKeyword_0; }
		
		//list+=STRING
		public Assignment getListAssignment_1() { return cListAssignment_1; }
		
		//STRING
		public RuleCall getListSTRINGTerminalRuleCall_1_0() { return cListSTRINGTerminalRuleCall_1_0; }
		
		//(',' list+=STRING )*
		public Group getGroup_2() { return cGroup_2; }
		
		//','
		public Keyword getCommaKeyword_2_0() { return cCommaKeyword_2_0; }
		
		//list+=STRING
		public Assignment getListAssignment_2_1() { return cListAssignment_2_1; }
		
		//STRING
		public RuleCall getListSTRINGTerminalRuleCall_2_1_0() { return cListSTRINGTerminalRuleCall_2_1_0; }
		
		//';'
		public Keyword getSemicolonKeyword_3() { return cSemicolonKeyword_3; }
	}
	
	
	private final StoryProgramElements pStoryProgram;
	private final StatementElements pStatement;
	private final NameStatementElements pNameStatement;
	private final EmotionStatementElements pEmotionStatement;
	private final VerbStatementElements pVerbStatement;
	private final AdverbStatementElements pAdverbStatement;
	private final LocationStatementElements pLocationStatement;
	private final AdjectiveStatementElements pAdjectiveStatement;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public StoryGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pStoryProgram = new StoryProgramElements();
		this.pStatement = new StatementElements();
		this.pNameStatement = new NameStatementElements();
		this.pEmotionStatement = new EmotionStatementElements();
		this.pVerbStatement = new VerbStatementElements();
		this.pAdverbStatement = new AdverbStatementElements();
		this.pLocationStatement = new LocationStatementElements();
		this.pAdjectiveStatement = new AdjectiveStatementElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("org.xtext.coursework.storyLang.Story".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//StoryProgram:
	//    statements += Statement*
	//;
	public StoryProgramElements getStoryProgramAccess() {
		return pStoryProgram;
	}
	
	public ParserRule getStoryProgramRule() {
		return getStoryProgramAccess().getRule();
	}
	
	//Statement:
	//    NameStatement |
	//    EmotionStatement |
	//    VerbStatement |
	//    AdverbStatement |
	//    AdjectiveStatement |
	//    LocationStatement
	//;
	public StatementElements getStatementAccess() {
		return pStatement;
	}
	
	public ParserRule getStatementRule() {
		return getStatementAccess().getRule();
	}
	
	//NameStatement:
	//    'name:' value=STRING ';'
	//;
	public NameStatementElements getNameStatementAccess() {
		return pNameStatement;
	}
	
	public ParserRule getNameStatementRule() {
		return getNameStatementAccess().getRule();
	}
	
	//EmotionStatement:
	//    'emotions:' list+=STRING (',' list+=STRING )* ';'
	//;
	public EmotionStatementElements getEmotionStatementAccess() {
		return pEmotionStatement;
	}
	
	public ParserRule getEmotionStatementRule() {
		return getEmotionStatementAccess().getRule();
	}
	
	//VerbStatement:
	//    'verb:' list+=STRING (',' list+=STRING )* ';'
	//;
	public VerbStatementElements getVerbStatementAccess() {
		return pVerbStatement;
	}
	
	public ParserRule getVerbStatementRule() {
		return getVerbStatementAccess().getRule();
	}
	
	//AdverbStatement:
	//    'adverbs:' list+=STRING (',' list+=STRING )* ';'
	//;
	public AdverbStatementElements getAdverbStatementAccess() {
		return pAdverbStatement;
	}
	
	public ParserRule getAdverbStatementRule() {
		return getAdverbStatementAccess().getRule();
	}
	
	//LocationStatement:
	//    'locations:' list+=STRING (',' list+=STRING )* ';'
	//;
	public LocationStatementElements getLocationStatementAccess() {
		return pLocationStatement;
	}
	
	public ParserRule getLocationStatementRule() {
		return getLocationStatementAccess().getRule();
	}
	
	//AdjectiveStatement:
	//    'adjectives:' list+=STRING (',' list+=STRING )* ';'
	//;
	public AdjectiveStatementElements getAdjectiveStatementAccess() {
		return pAdjectiveStatement;
	}
	
	public ParserRule getAdjectiveStatementRule() {
		return getAdjectiveStatementAccess().getRule();
	}
	
	//terminal ID: '^'?('a'..'z'|'A'..'Z'|'_') ('a'..'z'|'A'..'Z'|'_'|'0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt: ('0'..'9')+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//            '"' ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|'"') )* '"' |
	//            "'" ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|"'") )* "'"
	//        ;
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT : '/*' -> '*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT : '//' !('\n'|'\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS         : (' '|'\t'|'\r'|'\n')+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER: .;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
