/**
 * generated by Xtext 2.25.0
 */
package org.xtext.coursework.storyLang.story.impl;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

import org.eclipse.emf.ecore.impl.EPackageImpl;

import org.xtext.coursework.storyLang.story.AdjectiveStatement;
import org.xtext.coursework.storyLang.story.AdverbStatement;
import org.xtext.coursework.storyLang.story.EmotionStatement;
import org.xtext.coursework.storyLang.story.LocationStatement;
import org.xtext.coursework.storyLang.story.NameStatement;
import org.xtext.coursework.storyLang.story.Statement;
import org.xtext.coursework.storyLang.story.StoryFactory;
import org.xtext.coursework.storyLang.story.StoryPackage;
import org.xtext.coursework.storyLang.story.StoryProgram;
import org.xtext.coursework.storyLang.story.VerbStatement;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Package</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class StoryPackageImpl extends EPackageImpl implements StoryPackage
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass storyProgramEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass statementEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass nameStatementEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass emotionStatementEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass verbStatementEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass adverbStatementEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass locationStatementEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass adjectiveStatementEClass = null;

  /**
   * Creates an instance of the model <b>Package</b>, registered with
   * {@link org.eclipse.emf.ecore.EPackage.Registry EPackage.Registry} by the package
   * package URI value.
   * <p>Note: the correct way to create the package is via the static
   * factory method {@link #init init()}, which also performs
   * initialization of the package, or returns the registered package,
   * if one already exists.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.eclipse.emf.ecore.EPackage.Registry
   * @see org.xtext.coursework.storyLang.story.StoryPackage#eNS_URI
   * @see #init()
   * @generated
   */
  private StoryPackageImpl()
  {
    super(eNS_URI, StoryFactory.eINSTANCE);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private static boolean isInited = false;

  /**
   * Creates, registers, and initializes the <b>Package</b> for this model, and for any others upon which it depends.
   *
   * <p>This method is used to initialize {@link StoryPackage#eINSTANCE} when that field is accessed.
   * Clients should not invoke it directly. Instead, they should simply access that field to obtain the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #eNS_URI
   * @see #createPackageContents()
   * @see #initializePackageContents()
   * @generated
   */
  public static StoryPackage init()
  {
    if (isInited) return (StoryPackage)EPackage.Registry.INSTANCE.getEPackage(StoryPackage.eNS_URI);

    // Obtain or create and register package
    Object registeredStoryPackage = EPackage.Registry.INSTANCE.get(eNS_URI);
    StoryPackageImpl theStoryPackage = registeredStoryPackage instanceof StoryPackageImpl ? (StoryPackageImpl)registeredStoryPackage : new StoryPackageImpl();

    isInited = true;

    // Create package meta-data objects
    theStoryPackage.createPackageContents();

    // Initialize created meta-data
    theStoryPackage.initializePackageContents();

    // Mark meta-data to indicate it can't be changed
    theStoryPackage.freeze();

    // Update the registry and return the package
    EPackage.Registry.INSTANCE.put(StoryPackage.eNS_URI, theStoryPackage);
    return theStoryPackage;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getStoryProgram()
  {
    return storyProgramEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getStoryProgram_Statements()
  {
    return (EReference)storyProgramEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getStatement()
  {
    return statementEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getNameStatement()
  {
    return nameStatementEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getNameStatement_Value()
  {
    return (EAttribute)nameStatementEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getEmotionStatement()
  {
    return emotionStatementEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getEmotionStatement_List()
  {
    return (EAttribute)emotionStatementEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getVerbStatement()
  {
    return verbStatementEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getVerbStatement_List()
  {
    return (EAttribute)verbStatementEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getAdverbStatement()
  {
    return adverbStatementEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getAdverbStatement_List()
  {
    return (EAttribute)adverbStatementEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getLocationStatement()
  {
    return locationStatementEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getLocationStatement_List()
  {
    return (EAttribute)locationStatementEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getAdjectiveStatement()
  {
    return adjectiveStatementEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getAdjectiveStatement_List()
  {
    return (EAttribute)adjectiveStatementEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public StoryFactory getStoryFactory()
  {
    return (StoryFactory)getEFactoryInstance();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private boolean isCreated = false;

  /**
   * Creates the meta-model objects for the package.  This method is
   * guarded to have no affect on any invocation but its first.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void createPackageContents()
  {
    if (isCreated) return;
    isCreated = true;

    // Create classes and their features
    storyProgramEClass = createEClass(STORY_PROGRAM);
    createEReference(storyProgramEClass, STORY_PROGRAM__STATEMENTS);

    statementEClass = createEClass(STATEMENT);

    nameStatementEClass = createEClass(NAME_STATEMENT);
    createEAttribute(nameStatementEClass, NAME_STATEMENT__VALUE);

    emotionStatementEClass = createEClass(EMOTION_STATEMENT);
    createEAttribute(emotionStatementEClass, EMOTION_STATEMENT__LIST);

    verbStatementEClass = createEClass(VERB_STATEMENT);
    createEAttribute(verbStatementEClass, VERB_STATEMENT__LIST);

    adverbStatementEClass = createEClass(ADVERB_STATEMENT);
    createEAttribute(adverbStatementEClass, ADVERB_STATEMENT__LIST);

    locationStatementEClass = createEClass(LOCATION_STATEMENT);
    createEAttribute(locationStatementEClass, LOCATION_STATEMENT__LIST);

    adjectiveStatementEClass = createEClass(ADJECTIVE_STATEMENT);
    createEAttribute(adjectiveStatementEClass, ADJECTIVE_STATEMENT__LIST);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private boolean isInitialized = false;

  /**
   * Complete the initialization of the package and its meta-model.  This
   * method is guarded to have no affect on any invocation but its first.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void initializePackageContents()
  {
    if (isInitialized) return;
    isInitialized = true;

    // Initialize package
    setName(eNAME);
    setNsPrefix(eNS_PREFIX);
    setNsURI(eNS_URI);

    // Create type parameters

    // Set bounds for type parameters

    // Add supertypes to classes
    nameStatementEClass.getESuperTypes().add(this.getStatement());
    emotionStatementEClass.getESuperTypes().add(this.getStatement());
    verbStatementEClass.getESuperTypes().add(this.getStatement());
    adverbStatementEClass.getESuperTypes().add(this.getStatement());
    locationStatementEClass.getESuperTypes().add(this.getStatement());
    adjectiveStatementEClass.getESuperTypes().add(this.getStatement());

    // Initialize classes and features; add operations and parameters
    initEClass(storyProgramEClass, StoryProgram.class, "StoryProgram", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getStoryProgram_Statements(), this.getStatement(), null, "statements", null, 0, -1, StoryProgram.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(statementEClass, Statement.class, "Statement", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(nameStatementEClass, NameStatement.class, "NameStatement", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getNameStatement_Value(), ecorePackage.getEString(), "value", null, 0, 1, NameStatement.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(emotionStatementEClass, EmotionStatement.class, "EmotionStatement", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getEmotionStatement_List(), ecorePackage.getEString(), "list", null, 0, -1, EmotionStatement.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, !IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(verbStatementEClass, VerbStatement.class, "VerbStatement", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getVerbStatement_List(), ecorePackage.getEString(), "list", null, 0, -1, VerbStatement.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, !IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(adverbStatementEClass, AdverbStatement.class, "AdverbStatement", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getAdverbStatement_List(), ecorePackage.getEString(), "list", null, 0, -1, AdverbStatement.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, !IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(locationStatementEClass, LocationStatement.class, "LocationStatement", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getLocationStatement_List(), ecorePackage.getEString(), "list", null, 0, -1, LocationStatement.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, !IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(adjectiveStatementEClass, AdjectiveStatement.class, "AdjectiveStatement", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getAdjectiveStatement_List(), ecorePackage.getEString(), "list", null, 0, -1, AdjectiveStatement.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, !IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    // Create resource
    createResource(eNS_URI);
  }

} //StoryPackageImpl
