/**
 * generated by Xtext 2.30.0
 */
package org.xtext.coursework.storyLang;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class StoryStandaloneSetup extends StoryStandaloneSetupGenerated {
  public static void doSetup() {
    new StoryStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
