/**
 * generated by Xtext 2.25.0
 */
package org.xtext.coursework.storyLang.tests;

import org.eclipse.xtext.testing.InjectWith;
import org.eclipse.xtext.testing.extensions.InjectionExtension;
import org.junit.jupiter.api.extension.ExtendWith;

@ExtendWith(InjectionExtension.class)
@InjectWith(StoryInjectorProvider.class)
@SuppressWarnings("all")
public class StoryParsingTest {
}
