/**
 * generated by Xtext 2.30.0
 */
package org.xtext.coursework.storyLang.ide;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class StoryIdeModule extends AbstractStoryIdeModule {
}
