/**
 * generated by Xtext 2.25.0
 */
package org.xtext.coursework.storyLang.story;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Adjectives</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.coursework.storyLang.story.Adjectives#getAdjectives <em>Adjectives</em>}</li>
 * </ul>
 *
 * @see org.xtext.coursework.storyLang.story.StoryPackage#getAdjectives()
 * @model
 * @generated
 */
public interface Adjectives extends EObject
{
  /**
   * Returns the value of the '<em><b>Adjectives</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Adjectives</em>' attribute.
   * @see #setAdjectives(String)
   * @see org.xtext.coursework.storyLang.story.StoryPackage#getAdjectives_Adjectives()
   * @model
   * @generated
   */
  String getAdjectives();

  /**
   * Sets the value of the '{@link org.xtext.coursework.storyLang.story.Adjectives#getAdjectives <em>Adjectives</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Adjectives</em>' attribute.
   * @see #getAdjectives()
   * @generated
   */
  void setAdjectives(String value);

} // Adjectives
