/**
 * generated by Xtext 2.25.0
 */
package org.xtext.coursework.storyLang.story;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Adverbs</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.coursework.storyLang.story.Adverbs#getAdverbs <em>Adverbs</em>}</li>
 * </ul>
 *
 * @see org.xtext.coursework.storyLang.story.StoryPackage#getAdverbs()
 * @model
 * @generated
 */
public interface Adverbs extends EObject
{
  /**
   * Returns the value of the '<em><b>Adverbs</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Adverbs</em>' attribute.
   * @see #setAdverbs(String)
   * @see org.xtext.coursework.storyLang.story.StoryPackage#getAdverbs_Adverbs()
   * @model
   * @generated
   */
  String getAdverbs();

  /**
   * Sets the value of the '{@link org.xtext.coursework.storyLang.story.Adverbs#getAdverbs <em>Adverbs</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Adverbs</em>' attribute.
   * @see #getAdverbs()
   * @generated
   */
  void setAdverbs(String value);

} // Adverbs
