/**
 * generated by Xtext 2.30.0
 */
package org.xtext.coursework.storyLang.story;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Place Statement</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.coursework.storyLang.story.PlaceStatement#getValue <em>Value</em>}</li>
 * </ul>
 *
 * @see org.xtext.coursework.storyLang.story.StoryPackage#getPlaceStatement()
 * @model
 * @generated
 */
public interface PlaceStatement extends Statement
{
  /**
   * Returns the value of the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value</em>' attribute.
   * @see #setValue(String)
   * @see org.xtext.coursework.storyLang.story.StoryPackage#getPlaceStatement_Value()
   * @model
   * @generated
   */
  String getValue();

  /**
   * Sets the value of the '{@link org.xtext.coursework.storyLang.story.PlaceStatement#getValue <em>Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value</em>' attribute.
   * @see #getValue()
   * @generated
   */
  void setValue(String value);

} // PlaceStatement
