/**
 * generated by Xtext 2.25.0
 */
package org.xtext.coursework.storyLang.story;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see org.xtext.coursework.storyLang.story.StoryPackage
 * @generated
 */
public interface StoryFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  StoryFactory eINSTANCE = org.xtext.coursework.storyLang.story.impl.StoryFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Program</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Program</em>'.
   * @generated
   */
  StoryProgram createStoryProgram();

  /**
   * Returns a new object of class '<em>Statement</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Statement</em>'.
   * @generated
   */
  Statement createStatement();

  /**
   * Returns a new object of class '<em>Place Statement</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Place Statement</em>'.
   * @generated
   */
  PlaceStatement createPlaceStatement();

  /**
   * Returns a new object of class '<em>Path Statement</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Path Statement</em>'.
   * @generated
   */
  PathStatement createPathStatement();

  /**
   * Returns a new object of class '<em>Move Statement</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Move Statement</em>'.
   * @generated
   */
  MoveStatement createMoveStatement();

  /**
   * Returns a new object of class '<em>Nearby Statement</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Nearby Statement</em>'.
   * @generated
   */
  NearbyStatement createNearbyStatement();

  /**
   * Returns a new object of class '<em>Substance Statement</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Substance Statement</em>'.
   * @generated
   */
  SubstanceStatement createSubstanceStatement();

  /**
   * Returns a new object of class '<em>Mood Statement</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Mood Statement</em>'.
   * @generated
   */
  MoodStatement createMoodStatement();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  StoryPackage getStoryPackage();

} //StoryFactory
