/**
 * generated by Xtext 2.25.0
 */
package org.xtext.coursework.storyLang.story;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.coursework.storyLang.story.StoryFactory
 * @model kind="package"
 * @generated
 */
public interface StoryPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "story";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/coursework/storyLang/Story";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "story";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  StoryPackage eINSTANCE = org.xtext.coursework.storyLang.story.impl.StoryPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.coursework.storyLang.story.impl.StoryProgramImpl <em>Program</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.coursework.storyLang.story.impl.StoryProgramImpl
   * @see org.xtext.coursework.storyLang.story.impl.StoryPackageImpl#getStoryProgram()
   * @generated
   */
  int STORY_PROGRAM = 0;

  /**
   * The feature id for the '<em><b>Statements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STORY_PROGRAM__STATEMENTS = 0;

  /**
   * The number of structural features of the '<em>Program</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STORY_PROGRAM_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.coursework.storyLang.story.impl.StatementImpl <em>Statement</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.coursework.storyLang.story.impl.StatementImpl
   * @see org.xtext.coursework.storyLang.story.impl.StoryPackageImpl#getStatement()
   * @generated
   */
  int STATEMENT = 1;

  /**
   * The number of structural features of the '<em>Statement</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATEMENT_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.xtext.coursework.storyLang.story.impl.AmountStatementImpl <em>Amount Statement</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.coursework.storyLang.story.impl.AmountStatementImpl
   * @see org.xtext.coursework.storyLang.story.impl.StoryPackageImpl#getAmountStatement()
   * @generated
   */
  int AMOUNT_STATEMENT = 2;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AMOUNT_STATEMENT__VALUE = STATEMENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Amount Statement</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AMOUNT_STATEMENT_FEATURE_COUNT = STATEMENT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.coursework.storyLang.story.impl.PlaceStatementImpl <em>Place Statement</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.coursework.storyLang.story.impl.PlaceStatementImpl
   * @see org.xtext.coursework.storyLang.story.impl.StoryPackageImpl#getPlaceStatement()
   * @generated
   */
  int PLACE_STATEMENT = 3;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PLACE_STATEMENT__VALUE = STATEMENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Place Statement</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PLACE_STATEMENT_FEATURE_COUNT = STATEMENT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.coursework.storyLang.story.impl.PathStatementImpl <em>Path Statement</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.coursework.storyLang.story.impl.PathStatementImpl
   * @see org.xtext.coursework.storyLang.story.impl.StoryPackageImpl#getPathStatement()
   * @generated
   */
  int PATH_STATEMENT = 4;

  /**
   * The feature id for the '<em><b>List</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PATH_STATEMENT__LIST = STATEMENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Path Statement</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PATH_STATEMENT_FEATURE_COUNT = STATEMENT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.coursework.storyLang.story.impl.MoveStatementImpl <em>Move Statement</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.coursework.storyLang.story.impl.MoveStatementImpl
   * @see org.xtext.coursework.storyLang.story.impl.StoryPackageImpl#getMoveStatement()
   * @generated
   */
  int MOVE_STATEMENT = 5;

  /**
   * The feature id for the '<em><b>List</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MOVE_STATEMENT__LIST = STATEMENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Move Statement</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MOVE_STATEMENT_FEATURE_COUNT = STATEMENT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.coursework.storyLang.story.impl.NearbyStatementImpl <em>Nearby Statement</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.coursework.storyLang.story.impl.NearbyStatementImpl
   * @see org.xtext.coursework.storyLang.story.impl.StoryPackageImpl#getNearbyStatement()
   * @generated
   */
  int NEARBY_STATEMENT = 6;

  /**
   * The feature id for the '<em><b>List</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NEARBY_STATEMENT__LIST = STATEMENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Nearby Statement</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NEARBY_STATEMENT_FEATURE_COUNT = STATEMENT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.coursework.storyLang.story.impl.SubstanceStatementImpl <em>Substance Statement</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.coursework.storyLang.story.impl.SubstanceStatementImpl
   * @see org.xtext.coursework.storyLang.story.impl.StoryPackageImpl#getSubstanceStatement()
   * @generated
   */
  int SUBSTANCE_STATEMENT = 7;

  /**
   * The feature id for the '<em><b>List</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SUBSTANCE_STATEMENT__LIST = STATEMENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Substance Statement</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SUBSTANCE_STATEMENT_FEATURE_COUNT = STATEMENT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.coursework.storyLang.story.impl.MoodStatementImpl <em>Mood Statement</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.coursework.storyLang.story.impl.MoodStatementImpl
   * @see org.xtext.coursework.storyLang.story.impl.StoryPackageImpl#getMoodStatement()
   * @generated
   */
  int MOOD_STATEMENT = 8;

  /**
   * The feature id for the '<em><b>List</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MOOD_STATEMENT__LIST = STATEMENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Mood Statement</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MOOD_STATEMENT_FEATURE_COUNT = STATEMENT_FEATURE_COUNT + 1;


  /**
   * Returns the meta object for class '{@link org.xtext.coursework.storyLang.story.StoryProgram <em>Program</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Program</em>'.
   * @see org.xtext.coursework.storyLang.story.StoryProgram
   * @generated
   */
  EClass getStoryProgram();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.coursework.storyLang.story.StoryProgram#getStatements <em>Statements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Statements</em>'.
   * @see org.xtext.coursework.storyLang.story.StoryProgram#getStatements()
   * @see #getStoryProgram()
   * @generated
   */
  EReference getStoryProgram_Statements();

  /**
   * Returns the meta object for class '{@link org.xtext.coursework.storyLang.story.Statement <em>Statement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Statement</em>'.
   * @see org.xtext.coursework.storyLang.story.Statement
   * @generated
   */
  EClass getStatement();

  /**
   * Returns the meta object for class '{@link org.xtext.coursework.storyLang.story.AmountStatement <em>Amount Statement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Amount Statement</em>'.
   * @see org.xtext.coursework.storyLang.story.AmountStatement
   * @generated
   */
  EClass getAmountStatement();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.coursework.storyLang.story.AmountStatement#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see org.xtext.coursework.storyLang.story.AmountStatement#getValue()
   * @see #getAmountStatement()
   * @generated
   */
  EAttribute getAmountStatement_Value();

  /**
   * Returns the meta object for class '{@link org.xtext.coursework.storyLang.story.PlaceStatement <em>Place Statement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Place Statement</em>'.
   * @see org.xtext.coursework.storyLang.story.PlaceStatement
   * @generated
   */
  EClass getPlaceStatement();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.coursework.storyLang.story.PlaceStatement#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see org.xtext.coursework.storyLang.story.PlaceStatement#getValue()
   * @see #getPlaceStatement()
   * @generated
   */
  EAttribute getPlaceStatement_Value();

  /**
   * Returns the meta object for class '{@link org.xtext.coursework.storyLang.story.PathStatement <em>Path Statement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Path Statement</em>'.
   * @see org.xtext.coursework.storyLang.story.PathStatement
   * @generated
   */
  EClass getPathStatement();

  /**
   * Returns the meta object for the attribute list '{@link org.xtext.coursework.storyLang.story.PathStatement#getList <em>List</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>List</em>'.
   * @see org.xtext.coursework.storyLang.story.PathStatement#getList()
   * @see #getPathStatement()
   * @generated
   */
  EAttribute getPathStatement_List();

  /**
   * Returns the meta object for class '{@link org.xtext.coursework.storyLang.story.MoveStatement <em>Move Statement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Move Statement</em>'.
   * @see org.xtext.coursework.storyLang.story.MoveStatement
   * @generated
   */
  EClass getMoveStatement();

  /**
   * Returns the meta object for the attribute list '{@link org.xtext.coursework.storyLang.story.MoveStatement#getList <em>List</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>List</em>'.
   * @see org.xtext.coursework.storyLang.story.MoveStatement#getList()
   * @see #getMoveStatement()
   * @generated
   */
  EAttribute getMoveStatement_List();

  /**
   * Returns the meta object for class '{@link org.xtext.coursework.storyLang.story.NearbyStatement <em>Nearby Statement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Nearby Statement</em>'.
   * @see org.xtext.coursework.storyLang.story.NearbyStatement
   * @generated
   */
  EClass getNearbyStatement();

  /**
   * Returns the meta object for the attribute list '{@link org.xtext.coursework.storyLang.story.NearbyStatement#getList <em>List</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>List</em>'.
   * @see org.xtext.coursework.storyLang.story.NearbyStatement#getList()
   * @see #getNearbyStatement()
   * @generated
   */
  EAttribute getNearbyStatement_List();

  /**
   * Returns the meta object for class '{@link org.xtext.coursework.storyLang.story.SubstanceStatement <em>Substance Statement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Substance Statement</em>'.
   * @see org.xtext.coursework.storyLang.story.SubstanceStatement
   * @generated
   */
  EClass getSubstanceStatement();

  /**
   * Returns the meta object for the attribute list '{@link org.xtext.coursework.storyLang.story.SubstanceStatement#getList <em>List</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>List</em>'.
   * @see org.xtext.coursework.storyLang.story.SubstanceStatement#getList()
   * @see #getSubstanceStatement()
   * @generated
   */
  EAttribute getSubstanceStatement_List();

  /**
   * Returns the meta object for class '{@link org.xtext.coursework.storyLang.story.MoodStatement <em>Mood Statement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Mood Statement</em>'.
   * @see org.xtext.coursework.storyLang.story.MoodStatement
   * @generated
   */
  EClass getMoodStatement();

  /**
   * Returns the meta object for the attribute list '{@link org.xtext.coursework.storyLang.story.MoodStatement#getList <em>List</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>List</em>'.
   * @see org.xtext.coursework.storyLang.story.MoodStatement#getList()
   * @see #getMoodStatement()
   * @generated
   */
  EAttribute getMoodStatement_List();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  StoryFactory getStoryFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.coursework.storyLang.story.impl.StoryProgramImpl <em>Program</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.coursework.storyLang.story.impl.StoryProgramImpl
     * @see org.xtext.coursework.storyLang.story.impl.StoryPackageImpl#getStoryProgram()
     * @generated
     */
    EClass STORY_PROGRAM = eINSTANCE.getStoryProgram();

    /**
     * The meta object literal for the '<em><b>Statements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STORY_PROGRAM__STATEMENTS = eINSTANCE.getStoryProgram_Statements();

    /**
     * The meta object literal for the '{@link org.xtext.coursework.storyLang.story.impl.StatementImpl <em>Statement</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.coursework.storyLang.story.impl.StatementImpl
     * @see org.xtext.coursework.storyLang.story.impl.StoryPackageImpl#getStatement()
     * @generated
     */
    EClass STATEMENT = eINSTANCE.getStatement();

    /**
     * The meta object literal for the '{@link org.xtext.coursework.storyLang.story.impl.AmountStatementImpl <em>Amount Statement</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.coursework.storyLang.story.impl.AmountStatementImpl
     * @see org.xtext.coursework.storyLang.story.impl.StoryPackageImpl#getAmountStatement()
     * @generated
     */
    EClass AMOUNT_STATEMENT = eINSTANCE.getAmountStatement();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute AMOUNT_STATEMENT__VALUE = eINSTANCE.getAmountStatement_Value();

    /**
     * The meta object literal for the '{@link org.xtext.coursework.storyLang.story.impl.PlaceStatementImpl <em>Place Statement</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.coursework.storyLang.story.impl.PlaceStatementImpl
     * @see org.xtext.coursework.storyLang.story.impl.StoryPackageImpl#getPlaceStatement()
     * @generated
     */
    EClass PLACE_STATEMENT = eINSTANCE.getPlaceStatement();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PLACE_STATEMENT__VALUE = eINSTANCE.getPlaceStatement_Value();

    /**
     * The meta object literal for the '{@link org.xtext.coursework.storyLang.story.impl.PathStatementImpl <em>Path Statement</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.coursework.storyLang.story.impl.PathStatementImpl
     * @see org.xtext.coursework.storyLang.story.impl.StoryPackageImpl#getPathStatement()
     * @generated
     */
    EClass PATH_STATEMENT = eINSTANCE.getPathStatement();

    /**
     * The meta object literal for the '<em><b>List</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PATH_STATEMENT__LIST = eINSTANCE.getPathStatement_List();

    /**
     * The meta object literal for the '{@link org.xtext.coursework.storyLang.story.impl.MoveStatementImpl <em>Move Statement</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.coursework.storyLang.story.impl.MoveStatementImpl
     * @see org.xtext.coursework.storyLang.story.impl.StoryPackageImpl#getMoveStatement()
     * @generated
     */
    EClass MOVE_STATEMENT = eINSTANCE.getMoveStatement();

    /**
     * The meta object literal for the '<em><b>List</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MOVE_STATEMENT__LIST = eINSTANCE.getMoveStatement_List();

    /**
     * The meta object literal for the '{@link org.xtext.coursework.storyLang.story.impl.NearbyStatementImpl <em>Nearby Statement</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.coursework.storyLang.story.impl.NearbyStatementImpl
     * @see org.xtext.coursework.storyLang.story.impl.StoryPackageImpl#getNearbyStatement()
     * @generated
     */
    EClass NEARBY_STATEMENT = eINSTANCE.getNearbyStatement();

    /**
     * The meta object literal for the '<em><b>List</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute NEARBY_STATEMENT__LIST = eINSTANCE.getNearbyStatement_List();

    /**
     * The meta object literal for the '{@link org.xtext.coursework.storyLang.story.impl.SubstanceStatementImpl <em>Substance Statement</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.coursework.storyLang.story.impl.SubstanceStatementImpl
     * @see org.xtext.coursework.storyLang.story.impl.StoryPackageImpl#getSubstanceStatement()
     * @generated
     */
    EClass SUBSTANCE_STATEMENT = eINSTANCE.getSubstanceStatement();

    /**
     * The meta object literal for the '<em><b>List</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SUBSTANCE_STATEMENT__LIST = eINSTANCE.getSubstanceStatement_List();

    /**
     * The meta object literal for the '{@link org.xtext.coursework.storyLang.story.impl.MoodStatementImpl <em>Mood Statement</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.coursework.storyLang.story.impl.MoodStatementImpl
     * @see org.xtext.coursework.storyLang.story.impl.StoryPackageImpl#getMoodStatement()
     * @generated
     */
    EClass MOOD_STATEMENT = eINSTANCE.getMoodStatement();

    /**
     * The meta object literal for the '<em><b>List</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MOOD_STATEMENT__LIST = eINSTANCE.getMoodStatement_List();

  }

} //StoryPackage
