/**
 * generated by Xtext 2.30.0
 */
package org.xtext.coursework.storyLang.story;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.coursework.storyLang.story.StoryFactory
 * @model kind="package"
 * @generated
 */
public interface StoryPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "story";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/coursework/storyLang/Story";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "story";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  StoryPackage eINSTANCE = org.xtext.coursework.storyLang.story.impl.StoryPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.coursework.storyLang.story.impl.StoryProgramImpl <em>Program</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.coursework.storyLang.story.impl.StoryProgramImpl
   * @see org.xtext.coursework.storyLang.story.impl.StoryPackageImpl#getStoryProgram()
   * @generated
   */
  int STORY_PROGRAM = 0;

  /**
   * The feature id for the '<em><b>Statements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STORY_PROGRAM__STATEMENTS = 0;

  /**
   * The number of structural features of the '<em>Program</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STORY_PROGRAM_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.coursework.storyLang.story.impl.StatementImpl <em>Statement</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.coursework.storyLang.story.impl.StatementImpl
   * @see org.xtext.coursework.storyLang.story.impl.StoryPackageImpl#getStatement()
   * @generated
   */
  int STATEMENT = 1;

  /**
   * The number of structural features of the '<em>Statement</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATEMENT_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.xtext.coursework.storyLang.story.impl.NameStatementImpl <em>Name Statement</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.coursework.storyLang.story.impl.NameStatementImpl
   * @see org.xtext.coursework.storyLang.story.impl.StoryPackageImpl#getNameStatement()
   * @generated
   */
  int NAME_STATEMENT = 2;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NAME_STATEMENT__VALUE = STATEMENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Name Statement</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NAME_STATEMENT_FEATURE_COUNT = STATEMENT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.coursework.storyLang.story.impl.EmotionStatementImpl <em>Emotion Statement</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.coursework.storyLang.story.impl.EmotionStatementImpl
   * @see org.xtext.coursework.storyLang.story.impl.StoryPackageImpl#getEmotionStatement()
   * @generated
   */
  int EMOTION_STATEMENT = 3;

  /**
   * The feature id for the '<em><b>List</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EMOTION_STATEMENT__LIST = STATEMENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Emotion Statement</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EMOTION_STATEMENT_FEATURE_COUNT = STATEMENT_FEATURE_COUNT + 1;


  /**
   * Returns the meta object for class '{@link org.xtext.coursework.storyLang.story.StoryProgram <em>Program</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Program</em>'.
   * @see org.xtext.coursework.storyLang.story.StoryProgram
   * @generated
   */
  EClass getStoryProgram();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.coursework.storyLang.story.StoryProgram#getStatements <em>Statements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Statements</em>'.
   * @see org.xtext.coursework.storyLang.story.StoryProgram#getStatements()
   * @see #getStoryProgram()
   * @generated
   */
  EReference getStoryProgram_Statements();

  /**
   * Returns the meta object for class '{@link org.xtext.coursework.storyLang.story.Statement <em>Statement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Statement</em>'.
   * @see org.xtext.coursework.storyLang.story.Statement
   * @generated
   */
  EClass getStatement();

  /**
   * Returns the meta object for class '{@link org.xtext.coursework.storyLang.story.NameStatement <em>Name Statement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Name Statement</em>'.
   * @see org.xtext.coursework.storyLang.story.NameStatement
   * @generated
   */
  EClass getNameStatement();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.coursework.storyLang.story.NameStatement#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see org.xtext.coursework.storyLang.story.NameStatement#getValue()
   * @see #getNameStatement()
   * @generated
   */
  EAttribute getNameStatement_Value();

  /**
   * Returns the meta object for class '{@link org.xtext.coursework.storyLang.story.EmotionStatement <em>Emotion Statement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Emotion Statement</em>'.
   * @see org.xtext.coursework.storyLang.story.EmotionStatement
   * @generated
   */
  EClass getEmotionStatement();

  /**
   * Returns the meta object for the attribute list '{@link org.xtext.coursework.storyLang.story.EmotionStatement#getList <em>List</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>List</em>'.
   * @see org.xtext.coursework.storyLang.story.EmotionStatement#getList()
   * @see #getEmotionStatement()
   * @generated
   */
  EAttribute getEmotionStatement_List();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  StoryFactory getStoryFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.coursework.storyLang.story.impl.StoryProgramImpl <em>Program</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.coursework.storyLang.story.impl.StoryProgramImpl
     * @see org.xtext.coursework.storyLang.story.impl.StoryPackageImpl#getStoryProgram()
     * @generated
     */
    EClass STORY_PROGRAM = eINSTANCE.getStoryProgram();

    /**
     * The meta object literal for the '<em><b>Statements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STORY_PROGRAM__STATEMENTS = eINSTANCE.getStoryProgram_Statements();

    /**
     * The meta object literal for the '{@link org.xtext.coursework.storyLang.story.impl.StatementImpl <em>Statement</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.coursework.storyLang.story.impl.StatementImpl
     * @see org.xtext.coursework.storyLang.story.impl.StoryPackageImpl#getStatement()
     * @generated
     */
    EClass STATEMENT = eINSTANCE.getStatement();

    /**
     * The meta object literal for the '{@link org.xtext.coursework.storyLang.story.impl.NameStatementImpl <em>Name Statement</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.coursework.storyLang.story.impl.NameStatementImpl
     * @see org.xtext.coursework.storyLang.story.impl.StoryPackageImpl#getNameStatement()
     * @generated
     */
    EClass NAME_STATEMENT = eINSTANCE.getNameStatement();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute NAME_STATEMENT__VALUE = eINSTANCE.getNameStatement_Value();

    /**
     * The meta object literal for the '{@link org.xtext.coursework.storyLang.story.impl.EmotionStatementImpl <em>Emotion Statement</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.coursework.storyLang.story.impl.EmotionStatementImpl
     * @see org.xtext.coursework.storyLang.story.impl.StoryPackageImpl#getEmotionStatement()
     * @generated
     */
    EClass EMOTION_STATEMENT = eINSTANCE.getEmotionStatement();

    /**
     * The meta object literal for the '<em><b>List</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EMOTION_STATEMENT__LIST = eINSTANCE.getEmotionStatement_List();

  }

} //StoryPackage
