/**
 * generated by Xtext 2.25.0
 */
package org.xtext.coursework.storyLang.story;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Verb Statement</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.coursework.storyLang.story.VerbStatement#getList <em>List</em>}</li>
 * </ul>
 *
 * @see org.xtext.coursework.storyLang.story.StoryPackage#getVerbStatement()
 * @model
 * @generated
 */
public interface VerbStatement extends Statement
{
  /**
   * Returns the value of the '<em><b>List</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>List</em>' attribute list.
   * @see org.xtext.coursework.storyLang.story.StoryPackage#getVerbStatement_List()
   * @model unique="false"
   * @generated
   */
  EList<String> getList();

} // VerbStatement
