/**
 * generated by Xtext 2.25.0
 */
package org.xtext.coursework.storyLang.story;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Verbs</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.coursework.storyLang.story.Verbs#getVerbs <em>Verbs</em>}</li>
 * </ul>
 *
 * @see org.xtext.coursework.storyLang.story.StoryPackage#getVerbs()
 * @model
 * @generated
 */
public interface Verbs extends EObject
{
  /**
   * Returns the value of the '<em><b>Verbs</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Verbs</em>' attribute.
   * @see #setVerbs(String)
   * @see org.xtext.coursework.storyLang.story.StoryPackage#getVerbs_Verbs()
   * @model
   * @generated
   */
  String getVerbs();

  /**
   * Sets the value of the '{@link org.xtext.coursework.storyLang.story.Verbs#getVerbs <em>Verbs</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Verbs</em>' attribute.
   * @see #getVerbs()
   * @generated
   */
  void setVerbs(String value);

} // Verbs
