/*
 * generated by Xtext 2.25.0
 */
package org.xtext.coursework.storyLang.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.coursework.storyLang.parser.antlr.internal.InternalStoryParser;
import org.xtext.coursework.storyLang.services.StoryGrammarAccess;

public class StoryParser extends AbstractAntlrParser {

	@Inject
	private StoryGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalStoryParser createParser(XtextTokenStream stream) {
		return new InternalStoryParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "StoryProgram";
	}

	public StoryGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(StoryGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
