/*
 * generated by Xtext 2.25.0
 */
package org.xtext.coursework.storyLang.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import org.xtext.coursework.storyLang.ide.contentassist.antlr.internal.InternalStoryParser;
import org.xtext.coursework.storyLang.services.StoryGrammarAccess;

public class StoryParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(StoryGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, StoryGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getStatementAccess().getAlternatives(), "rule__Statement__Alternatives");
			builder.put(grammarAccess.getNameStatementAccess().getGroup(), "rule__NameStatement__Group__0");
			builder.put(grammarAccess.getEmotionStatementAccess().getGroup(), "rule__EmotionStatement__Group__0");
			builder.put(grammarAccess.getEmotionStatementAccess().getGroup_2(), "rule__EmotionStatement__Group_2__0");
			builder.put(grammarAccess.getVerbStatementAccess().getGroup(), "rule__VerbStatement__Group__0");
			builder.put(grammarAccess.getVerbStatementAccess().getGroup_2(), "rule__VerbStatement__Group_2__0");
			builder.put(grammarAccess.getAdverbStatementAccess().getGroup(), "rule__AdverbStatement__Group__0");
			builder.put(grammarAccess.getAdverbStatementAccess().getGroup_2(), "rule__AdverbStatement__Group_2__0");
			builder.put(grammarAccess.getLocationStatementAccess().getGroup(), "rule__LocationStatement__Group__0");
			builder.put(grammarAccess.getLocationStatementAccess().getGroup_2(), "rule__LocationStatement__Group_2__0");
			builder.put(grammarAccess.getAdjectiveStatementAccess().getGroup(), "rule__AdjectiveStatement__Group__0");
			builder.put(grammarAccess.getAdjectiveStatementAccess().getGroup_2(), "rule__AdjectiveStatement__Group_2__0");
			builder.put(grammarAccess.getStoryProgramAccess().getStatementsAssignment(), "rule__StoryProgram__StatementsAssignment");
			builder.put(grammarAccess.getNameStatementAccess().getValueAssignment_1(), "rule__NameStatement__ValueAssignment_1");
			builder.put(grammarAccess.getEmotionStatementAccess().getListAssignment_1(), "rule__EmotionStatement__ListAssignment_1");
			builder.put(grammarAccess.getEmotionStatementAccess().getListAssignment_2_1(), "rule__EmotionStatement__ListAssignment_2_1");
			builder.put(grammarAccess.getVerbStatementAccess().getListAssignment_1(), "rule__VerbStatement__ListAssignment_1");
			builder.put(grammarAccess.getVerbStatementAccess().getListAssignment_2_1(), "rule__VerbStatement__ListAssignment_2_1");
			builder.put(grammarAccess.getAdverbStatementAccess().getListAssignment_1(), "rule__AdverbStatement__ListAssignment_1");
			builder.put(grammarAccess.getAdverbStatementAccess().getListAssignment_2_1(), "rule__AdverbStatement__ListAssignment_2_1");
			builder.put(grammarAccess.getLocationStatementAccess().getListAssignment_1(), "rule__LocationStatement__ListAssignment_1");
			builder.put(grammarAccess.getLocationStatementAccess().getListAssignment_2_1(), "rule__LocationStatement__ListAssignment_2_1");
			builder.put(grammarAccess.getAdjectiveStatementAccess().getListAssignment_1(), "rule__AdjectiveStatement__ListAssignment_1");
			builder.put(grammarAccess.getAdjectiveStatementAccess().getListAssignment_2_1(), "rule__AdjectiveStatement__ListAssignment_2_1");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private StoryGrammarAccess grammarAccess;

	@Override
	protected InternalStoryParser createParser() {
		InternalStoryParser result = new InternalStoryParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public StoryGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(StoryGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
