/*
 * generated by Xtext 2.25.0
 */
package org.xtext.coursework.storyLang.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import org.xtext.coursework.storyLang.ide.contentassist.antlr.internal.InternalStoryParser;
import org.xtext.coursework.storyLang.services.StoryGrammarAccess;

public class StoryParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(StoryGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, StoryGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getVerbsAccess().getAlternatives(), "rule__Verbs__Alternatives");
			builder.put(grammarAccess.getNameAccess().getGroup(), "rule__Name__Group__0");
			builder.put(grammarAccess.getStoryProgramAccess().getStoriesAssignment(), "rule__StoryProgram__StoriesAssignment");
			builder.put(grammarAccess.getNameAccess().getNameAssignment_1(), "rule__Name__NameAssignment_1");
			builder.put(grammarAccess.getVerbsAccess().getVerbsAssignment_0(), "rule__Verbs__VerbsAssignment_0");
			builder.put(grammarAccess.getAdjectivesAccess().getAdjectivesAssignment(), "rule__Adjectives__AdjectivesAssignment");
			builder.put(grammarAccess.getAdverbsAccess().getAdverbsAssignment(), "rule__Adverbs__AdverbsAssignment");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private StoryGrammarAccess grammarAccess;

	@Override
	protected InternalStoryParser createParser() {
		InternalStoryParser result = new InternalStoryParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public StoryGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(StoryGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
